name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up Python and uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.13'
        activate-environment: true

    - name: Install dependencies
      run: uv pip install -r requirements.txt

    - name: Install test dependencies
      run: |
        uv pip install pytest pytest-asyncio aiosqlite httpx python-dotenv

    - name: Setup test environment
      run: |
        echo "DATABASE_URL=sqlite+aiosqlite:///data/app.db" > .env
        mkdir -p data
        cat .env

    - name: Run linter and formatter checks
      run: |
        uv pip install flake8 black
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        black . --check

    - name: Debug Print test file content
      run: cat tests/test_main.py

    - name: Run unit tests
      run: |
        PYTHONPATH=. pytest tests/ -v