name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python and uv
      uses: astral-sh/setup-uv@v6 # 使用官方提供的 setup-uv Action
      with:
        python-version: '3.9' # 指定 Python 版本
        # activate-environment: true # 如果需要自動啟動虛擬環境可以加上這行

    - name: Install dependencies
      run: uv pip install -r requirements.txt # 現在可以直接使用 uv 指令

    - name: Run linter and formatter checks
      run: |
        uv pip install flake8 black
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        black --check .

    - name: Run unit tests
      run: |
        uv pip install pytest
        pytest